import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🏭 基本架构',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '🏭 基本架构',
        },
      ],
    },
    {
      type: 'category',
      label: '🚀 部署',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '🚀 部署',
        },
      ],
    },
    {
      type: 'category',
      label: '📡 捕获服务',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '📡 捕获服务',
        },
      ],
    },
    {
      type: 'category',
      label: '⚖️ 负载均衡与转发',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '⚖️ 负载均衡与转发',
        },
      ],
    },
    {
      type: 'category',
      label: '💾 持久化数据库',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '💾 持久化数据库',
        },
      ],
    },
    {
      type: 'category',
      label: '🔍 HogQL',
      items: [
        {
          type: 'autogenerated',
          dirName: '🔍 HogQL',
        },
      ],
    }
  ],
};

export default sidebars;

