name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Swizzle Docusaurus components
        run: pnpm run swizzle @docusaurus/theme-classic -- --danger

      - name: Set build info
        run: |
          echo "NEXT_PUBLIC_BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BUILD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build website
        env:
          BUILD_TIME: ${{ env.NEXT_PUBLIC_BUILD_TIME }}
          BUILD_VERSION: ${{ env.NEXT_PUBLIC_BUILD_VERSION }}
        run: pnpm run build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          # 保持 Git 历史记录
          force_orphan: true 